#!/usr/bin/env python3
"""
campaign_link.py — Apple App Store Campaign Link Generator & Registry
Part of ios-marketing-ops.

Generates custom App Store attribution links with Campaign Tokens (?ct=...)
and records them into marketing/campaigns.csv for channel-by-channel tracking.
"""

import argparse
import csv
import datetime
import os
import re
import sys

def sanitize_token(token):
    # Apple Campaign Token: letters, numbers, hyphens, underscores (max 40 chars)
    cleaned = re.sub(r'[^a-zA-Z0-9_-]', '_', token)
    return cleaned[:40]

def main():
    parser = argparse.ArgumentParser(description="App Store Campaign Link Generator")
    parser.add_argument("--app", default="6449785515", help="App Store App ID (default: 6449785515)")
    parser.add_argument("--campaign", default="", help="Campaign identifier (e.g. reddit_post, tiktok_bio, x_thread)")
    parser.add_argument("--pt", default="", help="Provider Token (optional Apple developer token)")
    parser.add_argument("--channel", default="social", help="Channel tag (e.g. reddit, tiktok, twitter, blog, newsletter)")
    parser.add_argument("--store", default="marketing", help="Path to marketing directory")
    parser.add_argument("--self-check", action="store_true", help="Run self check")

    args = parser.parse_args()

    if args.self_check:
        tok = sanitize_token("Test Campaign 2026!#$")
        assert tok == "Test_Campaign_2026___"
        print("Self-check passed successfully.")
        return

    if not args.campaign:
        parser.error("the following arguments are required: --campaign")
        tok = sanitize_token("Test Campaign 2026!#$")
        assert tok == "Test_Campaign_2026___"
        print("Self-check passed successfully.")
        return

    ct = sanitize_token(args.campaign)
    base_url = f"https://apps.apple.com/app/id{args.app}"
    params = [f"ct={ct}"]
    if args.pt:
        params.append(f"pt={args.pt}")
    full_url = f"{base_url}?{'&'.join(params)}"

    # Append to marketing/campaigns.csv if store directory exists
    csv_dir = args.store
    if os.path.exists(csv_dir):
        csv_path = os.path.join(csv_dir, "campaigns.csv")
        exists = os.path.exists(csv_path)
        with open(csv_path, "a", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            if not exists:
                writer.writerow(["created_date", "campaign_token", "channel", "url", "note"])
            writer.writerow([
                datetime.date.today().isoformat(),
                ct,
                args.channel,
                full_url,
                f"Generated by ios-marketing-ops for {args.channel}"
            ])
        print(f"🔗 Registered campaign '{ct}' in {csv_path}")

    print("\n✅ GENERATED APP STORE CAMPAIGN LINK:")
    print(f"   {full_url}\n")
    print("📋 Where to view results:")
    print("   App Store Connect → App Analytics → Sources → Campaigns → " + ct)

if __name__ == "__main__":
    main()
